language: java
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    group: edge
    
  //- os: osx
  //  osx_image: xcode8
  
notifications:
  email: false
      
addons:
  apt:
    packages:
    - g++-multilib
    - lib32stdc++6
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
install: []
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- echo "Getting Maven Repo"
- git clone --depth=50 --branch=master https://github.com/pjreiniger/maven_repo.git ../../pjreiniger/maven_repo
- echo "Got it"
- "./gradlew build jacocoTestReport publish --refresh-dependencies -Pmaven_repo=../../pjreiniger/maven_repo"
- echo "built..."
- ls
- ls ..
- ls ../..
- ls ../../pjreiniger
- ls ../../pjreiniger/maven_repo

#after_success:
#  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: pwd; cd ../../pjreiniger/maven_repo; pwd; ls; chmod +x commit_updates.sh; ./commit_updates.sh
    skip_cleanup: true
    on:
      branch: master

env:
  global:
    secure: J81JK5zokRdrB8TfUC/sF0kXzrlAO7C2GN0nEOGJK22FMm0LlT/ECd1GrCjRWc/eHDQAXZVNliBVr9l5lXmt3iOxwAeBK/kMI/pxL5VMz7WelRBM8ibPtW5Tuj5JRpviCYygXVl8maOFVACWCovsZoJFot7DVEn+l20WfItmuZ0lyUmRT4+aS4OumxYO/LMS21Okw6xPYqixmb2MAetfmsDN13M2SUQY6KWbxUrrL3HyADSMLtI7ojquetAt0SBXBAnQ1VgLMvBw9Km4K2iKnKMUnEvadLGFFZu8Z2Q7bbDZyvKuU3KXeyzWFkskOmmw4cBw3egzfLXas+W4eJ9wOUnYrF5zI3VDP4tamDpLJEBalg36+dAy2eccQxbF5/4GRk4S5aLc0ZIkrVwWm+qc1Tht8oNCsesrVM5geQZRu3tUJgHECQu6Gc8ubCOVN8pAAVVZki5q1VHiLm08huAlVmnc7L549k1Y3Gj/qPc54enySSK0qAeCwult0cEO0w6KjahLGh+xqX08iWr/KXeZezM7HKcEMljnssCvp94VP7dhwjaskwd4Xw8e4n5yl2cLEGc+8MnvAeQXg9gnz1mn2fiBhAdMeTlnXgb6BrqiQ3toPTxOvOpzalBGL+93EPczlu2S1oNMEvxEFy9ATH236suuHQcEvbm9jebqPrbhi4k=
