version: 1.0.{build}
image: Visual Studio 2015

platform:
- x86
- x64

build_script:
- ps: >-
    mkdir build

    $ProgressPreference = 'SilentlyContinue'

    if ($env:PLATFORM -eq "x86") {
      echo "32 Bit"

      wget "https://github.com/wpilibsuite/frc-openjdk-windows/releases/download/v11.0.0u28-1/jdk-x86-11.0.0u28-1.zip" -O "build\jdk.zip"

      $Env:JAVA_HOME = "$pwd/build/jdkinst/jdk"
    }
    else {
      echo "64 bit"

      wget "https://download.java.net/java/ga/jdk11/openjdk-11_windows-x64_bin.zip" -O "build\jdk.zip"

      $Env:JAVA_HOME = "$pwd/build/jdkinst/jdk-11"
    }
    Expand-Archive build\jdk.zip -DestinationPath build/jdkinst

    dir

    dir build

    dir build\jdkinst

- cmd: gradlew.bat build jacocoTestReport publish -Pmaven_repo=build/maven_repo -PciBuild

after_build:
- cmd: "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- cmd: pip install codecov
- cmd: codecov -f "snobot_sim_gui/build/reports/jacoco/test/jacocoTestReport.xml"
- cmd: codecov -f "snobot_sim_java/build/reports/jacoco/test/jacocoTestReport.xml"
- cmd: codecov -f "snobot_sim_jni/build/reports/jacoco/test/jacocoTestReport.xml"

test_script:
- ps: >-
    # upload results to AppVeyor

    $wc = New-Object 'System.Net.WebClient'

    $files = Get-ChildItem ./snobot_sim_java/build/test-results/test/

    for ($i=0; $i -lt $files.Count; $i++) {

       $the_file = $files[$i].Name

       $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path snobot_sim_java/build/test-results/test/$the_file))

    }

    $files = Get-ChildItem ./snobot_sim_jni/build/test-results/test/

    for ($i=0; $i -lt $files.Count; $i++) {

       $the_file = $files[$i].Name

       $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path snobot_sim_jni/build/test-results/test/$the_file))

    }

    $files = Get-ChildItem ./snobot_sim_gui/build/test-results/test/

    for ($i=0; $i -lt $files.Count; $i++) {

       $the_file = $files[$i].Name

       $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path snobot_sim_gui/build/test-results/test/$the_file))

    }




artifacts:

- path: snobot_sim_gui/build/test-results
  name: testResults

- path: build/maven_repo/com/snobot/simulator/snobot_sim_jni/**/snobot_sim_jni-*.jar
  name: simulator_jni

- path: build/maven_repo/com/snobot/simulator/snobot_sim_java/**/snobot_sim_java-*.jar
  name: simulator_java

- path: build/maven_repo/com/snobot/simulator/snobot_sim_gui_application/**/snobot_sim_gui_application*.zip
  name: simulator_application

- path: build/maven_repo/com/snobot/simulator/snobot_sim_gui/**/snobot_sim_gui*.jar
  name: simulator_gui

- path: build/maven_repo/com/snobot/simulator/snobot_sim_gui_eclipse_boilerplate/**/snobot_sim_gui_eclipse_boilerplate-*.zip
  name: eciplse_boilerplate

- path: build/maven_repo
  name: full_maven_repo
